### ISSUE TITLE
Annotations and type aliases don't work

### ISSUE THREAD

**Issue by Mulugruntz** [kavigupta/ast_scope#3]
With the code:
```python
class A:
    pass

class B(A):
    pass

C = B
CONSTANT: C = C()
CONST: C
```

I'm expecting the following:
```python
# scope_info.static_dependency_graph._DiGraph__adjacency_list
{
    'A': set(),
    'B': set('A'),
    'C': set('B'),
    'CONSTANT': set('C'),
    'CONST': set('C'),
}
```

Instead I have:
```python
# scope_info.static_dependency_graph._DiGraph__adjacency_list
{
    'A': set(),
    'B': set('A'),
    'C': set(),
    'CONSTANT': set(),
    'CONST': set(),
}
```

I noticed in the code we don't implement `visit_Assign` and `visit_AnnAssign`. We also don't do `visit_AugAssign` btw.

**Comment by kavigupta** [comment]
I know this issue is really old, sorry I didn't see it. The issue is the inverse, the correct solution should be

{
    'A': set(),
    'B': set(),
    'C': set(),
    'CONSTANT': set(),
    'CONST': set(),
}

The dependency here is not dataflow but rather which scopes are nested within which other scopes. No scopes are nested here, so there should be no edges in the dependency graph
